export const DEFAULT_REMOTE_HOST = '127.0.0.1'
export const DEFAULT_REMOTE_PORT = 18765
export const DEFAULT_REMOTE_PASSTHROUGH_ONLY = true
export const DEFAULT_REMOTE_IDLE_TIMEOUT_MS = 30 * 60 * 1000
export const DEFAULT_REMOTE_RATE_LIMIT_WINDOW_MS = 60 * 1000
export const DEFAULT_REMOTE_RATE_LIMIT_MAX = 240
export const DEFAULT_REMOTE_TOKEN_FILE = 'remote-token.txt'
export const REMOTE_SERVICE_CONFIG_FILE = 'remote-service-config.json'
export const REMOTE_SERVICE_SECRETS_FILE = 'remote-service-secrets.json'
export const CLOUDFLARE_TUNNEL_CONFIG_FILE = 'cloudflare-tunnel-config.json'
export const REMOTE_NETWORK_SETTINGS_FILE = 'remote-network-settings.json'
export const REMOTE_NETWORK_RUNTIME_FILE = 'remote-network-runtime.json'
